DEBUG: True
SECRET_KEY: "django-secret-key"
PGHOST: "postgres-host"
PGDATABASE: "postgres-database-name"
PGUSER: "postgres-username"
PGPASSWORD: "postgres-password"
PGSSLMODE: "require"
PGCHANNELBINDING: "require"
PGPORT: 5432
HOST: "127.0.0.1"     #backend api host url
ALLOWED_HOSTS:
    - "127.0.0.1"
    - "localhost"
ACCESS_TOKEN_LIFETIME: "30"                       # minutes
REFRESH_TOKEN_LIFETIME: "30"                      # days
EMAIL_HOST: "smtp.gmail.com"                      # mail host
EMAIL_HOST_USER: "username"                       # mail user
EMAIL_HOST_PASSWORD: "password"                   # mail password
EMAIL_PORT: 587                                   # mail port          
EMAIL_USE_TLS: True
SERVER_EMAIL: "server@example.com"                # server email
DEFAULT_FROM_EMAIL: "no-reply@example.com"        # from email
ADMINS:
    - ["Admin 1", "admin1@example.com"]     
    - ["Admin 2", "admin2@example.com"]

GOOGLE_CLIENT_ID: "google-client-id-for-google-login"
GOOGLE_CLIENT_SECRET: "google-client-secret-for-google-login"

FACEBOOK_CLIENT_ID: "facebook-client-id-for-facebook-login"
FACEBOOK_CLIENT_SECRET: "facebook-client-secret-for-facebook-login"

GITHUB_CLIENT_ID: "github-client-id-for-github-login"
GITHUB_CLIENT_SECRET: "github-client-secret-for-github-login"

LINKEDIN_CLIENT_ID: "linkedin-client-id-for-linkedin-login"
LINKEDIN_CLIENT_SECRET: "linkedin-client-secret-for-linkedin-login"

OAUTH_REDIRECT_URI: "http://localhost:5173/auth/callback"       # update url in google, facebook, github and linkedin Apps. 

CORS_ALLOWED_ORIGINS:
    - "http://localhost:3000/"                    # frontend url for CORS
    - "http://localhost:5173/"                    # frontend url for CORS